#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
polybar &

bspc monitor -d ● ● ● ● ●

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config border_radius		5

bspc config normal_border_color		"#6C7086"
bspc config focused_border_color	"#B4BEFE"

bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
